namespace TradeBlazorApp.Data_Classes
{

    //All code generated by CHatGTP Interaction 27, for entire class, from SQL Server DDL table HOLDING
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("HOLDING", Schema = "dbo")]
    public class Holding
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // Use None if HOLDINGID is provided by the application
        [Column("HOLDINGID", TypeName = "uniqueidentifier")]
        public Guid HoldingId { get; set; }

        [Column("PURCHASEPRICE", TypeName = "decimal(12, 2)")]
        public decimal? PurchasePrice { get; set; }

        [Column("QUANTITY", TypeName = "float")]
        [Required]
        public double Quantity { get; set; } // float in SQL Server is mapped to double in C#

        [Column("PURCHASEDATE", TypeName = "datetime")]
        public DateTime? PurchaseDate { get; set; }

        [Column("ACCOUNT_ACCOUNTID", TypeName = "bigint")]
        [Required]
        public long AccountAccountId { get; set; } // Assuming this is a foreign key to another table

        [Column("QUOTE_SYMBOL", TypeName = "varchar(10)")]
        public string QuoteSymbol { get; set; }

        [Column("USERID", TypeName = "varchar(50)")]
        [Required]
        public string UserId { get; set; }

        // Navigation properties and any additional columns go here
    }

}
