namespace TradeBlazorApp.Data_Classes
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ORDERS")] // Adjust the table name as per your database schema
    //I CHanged to all Caps "ORDERS" from ChatGTP generated class interaction 24
    public class Order
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Assuming ORDERID is auto-generated. Adjust as necessary.
        public Guid ORDERID { get; set; }

        public long ACCOUNT_ACCOUNTID { get; set; } // Foreign key relation, adjust the type as necessary --/I had to change this type to "long"  ChatGTP created as Guid
                                                    //Likely becuase it seems to do so for anything autogenerated as a KEY by SQL Server(??)
        public DateTime COMPLETIONDATE { get; set; }
        public Guid HOLDING_HOLDINGID { get; set; } // Foreign key relation, adjust as necessary
        public DateTime OPENDATE { get; set; }
        public decimal ORDERFEE { get; set; }
        [MaxLength(10)]
        public string ORDERSTATUS { get; set; }
        [MaxLength(10)]
        public string ORDERTYPE { get; set; }
        [MaxLength(10)]
        public string QUOTE_SYMBOL { get; set; } // Adjust the MaxLength as per your column definition
        public decimal PRICE { get; set; }
        public int QUANTITY { get; set; }
        public string USERID { get; set; } // Adjust the type as necessary

        // Navigation properties and any additional columns go here
    }

}
