namespace TradeBlazorApp.Data_Classes
{

    //This entire class generated by ChatGPT in interaction 23
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("QUOTE", Schema = "dbo")]
    public class Quote
    {
        [Column("LOW", TypeName = "decimal(12, 2)")]
        public decimal? Low { get; set; }

        [Column("OPEN1", TypeName = "decimal(12, 2)")]
        public decimal? Open1 { get; set; }

        [Column("VOLUME", TypeName = "float")]
        [Required]
        public float Volume { get; set; }

        [Column("PRICE", TypeName = "decimal(12, 2)")]
        public decimal Price { get; set; }

        [Column("HIGH", TypeName = "decimal(12, 2)")]
        public decimal? High { get; set; }

        [Column("COMPANYNAME", TypeName = "varchar(250)")]
        public string CompanyName { get; set; }

        //[Key]  Commenting out to avoid composite key issue, rather creating in an override method the composite key  
        [Column("SYMBOL", TypeName = "varchar(10)", Order = 0)]
        [Required]
        public string Symbol { get; set; }

        [Column("CHANGE1", TypeName = "float")]
        [Required]
        public float Change1 { get; set; }

        //[Key]  Commenting out to avoid composite key issue, rather creating in an override method the composite key  [Key]
        [Column("QUOTEID", TypeName = "bigint", Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // Assuming QUOTEID is not auto-generated
        public long QuoteId { get; set; }
    }

}
