using TradeBlazorApp.Data_Classes;

namespace TradeBlazorApp.Business_Classes
{
    //The entire class code was completely generated by ChatGTP Interaction 4, from VB.NET app.
    //No changes required.  Howevet, it references a type/class AccountCurrent, that is not migraed yet, so will not compile yet.

    public class GlobalSettings
    {
        public static bool LoggedIn { get; set; }
        public static AccountProfile theLoginAccount { get; set; }

        public static Quote theCurrentQuote { get; set; }   //Added per ChatGTP Interaction 66

        public static Holding theCurrentHolding { get; set; }   //Added per ChatGTP Interaction 66
    }

}
